spring:
  application:
    name: movieflix

  datasource:
    url: jdbc:postgresql://localhost:5433/movieflix
    username: username
    password: userpass

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true

movieflix:
  security:
    jwt:
      secret: "MYHASHEDKEY"